[project]
name = "nx-workspace"
version = "1.0.0"
dependencies = [ "mochidasu-agent", "mochidasu-agent-connection" ]

[tool.uv.workspace]
members = [ "packages/agent", "packages/common/agent_connection" ]

[tool.uv.sources.mochidasu-agent]
workspace = true

[tool.uv.sources.mochidasu-agent-connection]
workspace = true

[dependency-groups]
dev = [
  "ruff==0.16.6",
  "autopep8>=2.3.1",
  "pytest>=8.3.4",
  "pytest-sugar>=1.0.0",
  "pytest-cov>=6.0.0",
  "pytest-html>=4.1.1",
  "ty==0.0.78"
]
